name: "Java CI"

on: ["pull_request", "push"]

jobs:
  preserve:
    runs-on: "ubuntu-latest"
    steps:
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: "ubuntu-latest"
    steps: 
      - uses: "actions/checkout@v2.3.4"
        with:
          fetch-depth: 0
      - name: Lint files changed.
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: "1.16"  
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # build:
